# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Potctl < Formula
  desc "CLI for managing Datasance PoT's Distributed Edge Compute clusters"
  homepage "https://github.com/datasance/potctl"
  version "1.6.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datasance/potctl/releases/download/v1.6.3/potctl_1.6.3_macos_amd64.tar.gz"
      sha256 "fa232e2326197b29d8e992a6dc10daa67e178c34cd27a2410c9382ff35b0054e"

      define_method(:install) do
        bin.install "potctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datasance/potctl/releases/download/v1.6.3/potctl_1.6.3_macos_arm64.tar.gz"
      sha256 "eb2999945a5b7b137760f02a4639ce4170335267f5c054590a204f0c4a0924a0"

      define_method(:install) do
        bin.install "potctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datasance/potctl/releases/download/v1.6.3/potctl_1.6.3_amd64.tar.gz"
      sha256 "0c967ee14e3d7d38ee18400b8b20665e5a0fd42d1b53505313c842e6c84c5614"
      define_method(:install) do
        bin.install "potctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/datasance/potctl/releases/download/v1.6.3/potctl_1.6.3_armv6.tar.gz"
      sha256 "86946873c609a7b16315a9d82368236d8238268fcf8642ae7266daa1b985e76e"
      define_method(:install) do
        bin.install "potctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datasance/potctl/releases/download/v1.6.3/potctl_1.6.3_arm64.tar.gz"
      sha256 "8ba1b2b9542f581cfe30890f5a6ae85a57fd1c10b665fe13ff990d711aff58e5"
      define_method(:install) do
        bin.install "potctl"
      end
    end
  end

  test do
    system "#{bin}/potctl version"
  end
end
