# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Potctl < Formula
  desc "CLI for managing Datasance PoT's Distributed Edge Compute clusters"
  homepage "https://github.com/datasance/potctl"
  version "1.3.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datasance/potctl/releases/download/v1.3.7/potctl_1.3.7_macos_amd64.tar.gz"
      sha256 "beebf6a675db11be70af872b365aa854dd5973bef27c44d3de29dd7c682af803"

      def install
        bin.install "potctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/datasance/potctl/releases/download/v1.3.7/potctl_1.3.7_armv6.tar.gz"
      sha256 "321ad5dd72ab024e66479939ea83e1752d9623a692eaeb2a7605543bd5d6a038"

      def install
        bin.install "potctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/datasance/potctl/releases/download/v1.3.7/potctl_1.3.7_amd64.tar.gz"
      sha256 "b56cb8679bec90b130aa345afef94dcf9e4a2887f9f47725b964af5584f51568"

      def install
        bin.install "potctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datasance/potctl/releases/download/v1.3.7/potctl_1.3.7_arm64.tar.gz"
      sha256 "87b23728cd90c724efd83fcbfb65bfee8aedf1230d06a282667c9effc5e08f8b"

      def install
        bin.install "potctl"
      end
    end
  end

  test do
    system "#{bin}/potctl version"
  end
end
